#!/bin/sh
# commit-msg
#
# This hook verifies that the commit message contains a reference to a Jira ID

# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux/20983251#20983251
# COLOUR sets the colour in console to a selected colour for this text
# NORMAL sets the colour in console to default for this text
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
NORMAL=$(tput sgr0)

# Regex to validate a string contains "chrp-" followed by 4 or 5 digits anywhere in the commit message
regex="chrp-[0-9]{4,5}($|[^0-9])"

file=`cat $1` # The file that contains the commit message

# If the commit message does not match the regex
# The ,, operator for parameter expansion will convert the entire variable to lowercase for the purpose of the comparison
if ! [[ ${file,,} =~ $regex ]]; then

  echo "${RED}ERROR - Missing Jira ID in commmit message. E.g. '[CHRP-12345] xyz chnages made'.$NORMAL"
  exit 1
else
  echo "${GREEN}Commit message passed Jira ID validation.$NORMAL"
fi

exit 0